Improve rfc command integrations
 - Improve the rfc script
   - Add better arg handling
   - Allow multiple rfcs
   - Allow a download-only version
 - Add command to vim that runs rfc script

diff --git a/scripts/rfc b/scripts/rfc
--- a/scripts/rfc
+++ b/scripts/rfc
@@ -2,21 +2,74 @@
 
 RFCDIR=$HOME/.local/share/rfcs
 
-if ! [ -f $RFCDIR/rfc$1.txt ]
+RFCS=""
+RFC_TXTS=""
+NUM_RFCS=0
+QUIET=0
+
+while :
+do
+    case "$1" in
+        -q | --quiet)
+            QUIET=1
+            shift
+            ;;
+        -h | --help)
+            echo "$0 <rfc num>"
+            exit 0
+            ;;
+        -*)
+            echo "Unknown option: $1"
+            echo "$0 <rfc num>"
+            exit 1
+            ;;
+        *)
+            RFCS=$@
+            break
+            ;;
+    esac
+done
+
+re='^[0-9]+$'
+for rfc in ${RFCS[@]}
+do
+    if ! [[ $rfc =~ $re ]]
+    then
+        echo "$rfc is not a number"
+        exit 1
+    else
+        if ! [ -f $RFCDIR/rfc$rfc.txt ]
+        then
+            echo "Downloading RFC: $rfc"
+            curl https://tools.ietf.org/rfc/rfc$rfc.txt -o $RFCDIR/rfc$rfc.txt
+            if [ $? -ne 0 ]
+            then
+                echo "Could not download rfc$1!"
+                exit 1
+            fi
+            sed -i 's/[\x0c\x0d]//g' $RFCDIR/rfc$rfc.txt
+        fi
+        RFC_TXTS="$RFC_TXTS $RFCDIR/rfc$rfc.txt"
+    fi
+    ((NUM_RFCS=NUM_RFCS+1))
+done
+
+if [ $QUIET -eq 0 ]
 then
-    echo "Downloading RFC: $1"
-    curl https://tools.ietf.org/rfc/rfc$1.txt | sed 's/[\x0c\x0d]//g' > $RFCDIR/rfc$1.txt
-    if [ $? -ne 0 ]
+    if ! [ -f $RFCDIR/rfc$1.txt ]
     then
         echo "Could not download rfc$1!"
         exit 1
+    else
+        if [ $NUM_RFCS -eq 0 ]
+        then
+            echo "Must specify at least one rfc"
+            exit 1
+        elif [ $NUM_RFCS -eq 1 ]
+        then
+            vi -c "setfiletype rfc" -R $RFC_TXTS
+        else
+            vi -o 1 -c "setfiletype rfc" -R $RFC_TXTS
+        fi
     fi
-fi
-
-if ! [ -f $RFCDIR/rfc$1.txt ]
-then
-    echo "Could not download rfc$1!"
-    exit 1
-else
-    vi -R $RFCDIR/rfc$1.txt
 fi
